spring:
  datasource:
    url: jdbc:h2:mem:award_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
